/**
 * P2P social layer — SHARED TypeScript contract (base branch
 * `feat/p2p-social-base`).
 *
 * Mirrors the Rust shared types in `src-tauri/src/servitude/social/mod.rs`.
 * The Rust side serializes every field camelCase (`#[serde(rename_all =
 * "camelCase")]`), so these interfaces match the wire shape 1:1 with no
 * transcription needed.
 *
 * OWNERSHIP: this file is SHARED — it lives in the base branch and is frozen
 * after the base lands. Each of the four feature branches owns its own
 * sibling api file (`social/superuser.ts`, `social/peers.ts`, `social/inbox.ts`,
 * `social/consolidate.ts`) and its own component subtree. They IMPORT these
 * types; they do NOT edit this file.
 */

/** Stable owner id — lowercase hex of the install's Ed25519 public key. */
export type OwnerId = string;
/** Libp2p peer id (base58 multihash). */
export type PeerId = string;
/** ULID device id. */
export type DeviceId = string;
/** RFC3339 timestamp string (lexicographically sortable). */
export type Rfc3339 = string;

/** Trust level a tracked peer holds in the social graph. */
export type SocialTrust =
  | "unknown"
  | "recent"
  | "friend"
  | "closeFriend"
  | "supertrusted";

/** Direction of a 1:1 inbox message relative to the owner. */
export type MessageDirection = "outbound" | "inbound";

/** The authoritative owner ("superuser") profile. Owned by superuser-ux. */
export interface OwnerIdentity {
  ownerId: OwnerId;
  displayName: string;
  bio?: string | null;
  avatarRef?: string | null;
  claimed: boolean;
  claimedAt?: Rfc3339 | null;
}

/** A peer the owner knows about. Owned by known-peers-registry. */
export interface PeerRecord {
  peerId: PeerId;
  publicKeyHex: string;
  label?: string | null;
  trust: SocialTrust;
  firstSeen: Rfc3339;
  lastSeen: Rfc3339;
  multiaddrs: string[];
}

/** One message in a per-peer 1:1 conversation. Owned by per-peer-inboxes. */
export interface InboxMessage {
  id: string;
  peerId: PeerId;
  direction: MessageDirection;
  body: string;
  sentAt: Rfc3339;
  read: boolean;
}

/** Per-peer conversation summary. Owned by per-peer-inboxes. */
export interface ConversationRecord {
  peerId: PeerId;
  unread: number;
  lastMessageAt?: Rfc3339 | null;
  lastPreview?: string | null;
}

/** A device claiming the same owner. Owned by multi-device-consolidation. */
export interface DeviceIdentity {
  deviceId: DeviceId;
  ownerId: OwnerId;
  peerId: PeerId;
  label?: string | null;
  lastSyncAt?: Rfc3339 | null;
}

/** A pending consolidation proposal. Owned by multi-device-consolidation. */
export interface ConsolidationProposal {
  id: string;
  localDevice: DeviceIdentity;
  remoteDevice: DeviceIdentity;
  conflicts: string[];
}
