/**
 * P2P social layer — SHARED TypeScript contract (base branch
 * `feat/p2p-social-base`).
 *
 * Mirrors the Rust shared types in `src-tauri/src/servitude/social/mod.rs`.
 * The Rust side serializes every field camelCase (`#[serde(rename_all =
 * "camelCase")]`), so these interfaces match the wire shape 1:1 with no
 * transcription needed.
 *
 * OWNERSHIP: this file is SHARED — it lives in the base branch and is frozen
 * after the base lands. Each of the four feature branches owns its own
 * sibling api file (`social/superuser.ts`, `social/peers.ts`, `social/inbox.ts`,
 * `social/consolidate.ts`) and its own component subtree. They IMPORT these
 * types; they do NOT edit this file.
 */

/** Stable owner id — lowercase hex of the install's Ed25519 public key. */
export type OwnerId = string;
/** Libp2p peer id (base58 multihash). */
export type PeerId = string;
/** ULID device id. */
export type DeviceId = string;
/** RFC3339 timestamp string (lexicographically sortable). */
export type Rfc3339 = string;

/** Trust level a tracked peer holds in the social graph. */
export type SocialTrust =
  | "unknown"
  | "recent"
  | "friend"
  | "closeFriend"
  | "supertrusted";

/** Direction of a 1:1 inbox message relative to the owner. */
export type MessageDirection = "outbound" | "inbound";

/**
 * Live-delivery state of an outbound inbox message (mirrors the Rust
 * `DeliveryStatus`, `#[serde(default)] = delivered`). Additive: rows
 * serialized before the field existed omit it, so it is optional here and
 * absent means "delivered".
 *
 * "sent" = written to the wire with no ack back (peer speaks only 1.0.0, or
 * the ack has not landed). Never render "sent" as "delivered".
 * "refused" = the peer's pairing gate dropped the body; not retried.
 * "failed" = terminal transport verdict; the reconnect flush skips it.
 */
export type DeliveryStatus =
  | "pending"
  | "sent"
  | "delivered"
  | "refused"
  | "failed";

/** The authoritative owner ("superuser") profile. Owned by superuser-ux. */
export interface OwnerIdentity {
  ownerId: OwnerId;
  displayName: string;
  bio?: string | null;
  avatarRef?: string | null;
  claimed: boolean;
  claimedAt?: Rfc3339 | null;
}

/** A peer the owner knows about. Owned by known-peers-registry. */
export interface PeerRecord {
  peerId: PeerId;
  publicKeyHex: string;
  label?: string | null;
  trust: SocialTrust;
  firstSeen: Rfc3339;
  lastSeen: Rfc3339;
  multiaddrs: string[];
}

/**
 * One emoji's aggregated reactions on a message (mirrors Rust
 * `MessageReaction`). In a 1:1 conversation `count` is 1 or 2 and `mine`
 * drives "tap again to retract".
 */
export interface MessageReaction {
  emoji: string;
  count: number;
  mine: boolean;
}

/** One stored attachment (mirrors Rust `InboxAttachment`). */
export interface InboxAttachment {
  id: string;
  messageId: string;
  fileName: string;
  /** SNIFFED media type — never the peer's claim. */
  mime: string;
  byteSize: number;
  sha256: string;
  /** Only when true may a surface try to render the bytes inline. */
  isImage: boolean;
  /** Absolute path to the blob inside the app's attachment directory. */
  path: string;
}

/** One message in a per-peer 1:1 conversation. Owned by per-peer-inboxes. */
export interface InboxMessage {
  id: string;
  peerId: PeerId;
  direction: MessageDirection;
  body: string;
  sentAt: Rfc3339;
  read: boolean;
  /** Delivery state for outbound rows; absent/omitted = "delivered". */
  delivery?: DeliveryStatus;
  /** Media attached to this message, when there is any (1.2). */
  attachment?: InboxAttachment | null;
  /** Body edited at least once; render an "(edited)" marker (1.2). */
  edited?: boolean;
  /** Tombstone — render "message deleted" in place of the body (1.2). */
  deleted?: boolean;
  /** Composed as a reply to another message (1.2). */
  isReply?: boolean;
  /**
   * Display snippet of the replied-to message, resolved at read time.
   * `null` while `isReply` means the original is unavailable — say so
   * rather than invent a quote (1.2).
   */
  replySnippet?: string | null;
  /** Aggregated reactions, one entry per distinct emoji (1.2). */
  reactions?: MessageReaction[];
  /**
   * GROUPS — the authenticated author, only on inbound rows of a group
   * conversation (where `peerId` is the group id).
   */
  senderPeer?: PeerId | null;
}

/** Per-peer conversation summary. Owned by per-peer-inboxes. */
export interface ConversationRecord {
  peerId: PeerId;
  unread: number;
  lastMessageAt?: Rfc3339 | null;
  lastPreview?: string | null;
  /** This row is a GROUP conversation; `peerId` is the group id. */
  isGroup?: boolean;
  groupName?: string | null;
  memberCount?: number;
  /** The owner was removed from (or left) this group; read-only surface. */
  removed?: boolean;
}

/**
 * Ack of a local transcript mutation (edit / delete / reaction toggle) —
 * mirrors the shell's `InboxMutationAck`. `queued` says a wire update was
 * queued for the peer; `added` (reaction toggles only) says the reaction is
 * now present.
 */
export interface InboxMutationAck {
  peerId: PeerId;
  queued: boolean;
  added: boolean;
}

/** A device claiming the same owner. Owned by multi-device-consolidation. */
export interface DeviceIdentity {
  deviceId: DeviceId;
  ownerId: OwnerId;
  peerId: PeerId;
  label?: string | null;
  lastSyncAt?: Rfc3339 | null;
}

/** A pending consolidation proposal. Owned by multi-device-consolidation. */
export interface ConsolidationProposal {
  id: string;
  localDevice: DeviceIdentity;
  remoteDevice: DeviceIdentity;
  conflicts: string[];
}
